-- ## ADD COLUMN
ALTER TABLE student 
ADD school_id INTEGER;

-- ## RENAME COLUMN
ALTER TABLE student 
RENAME COLUMN school_id TO school;

-- ## DROP COLUMN
ALTER TABLE student
DROP COLUMN school_id;

-- ## CHANGE COLUMN DATA TYPE
ALTER TABLE student
ALTER COLUMN school_id 
TYPE VARCHAR(20);

-- ## SET COLUMN DEFAULT VALUE
ALTER TABLE student
ALTER COLUMN school_id
SET DEFAULT 2;

-- ## DROP COLUMN DEFAULT VALUE
ALTER TABLE student
ALTER COLUMN school_id
DROP DEFAULT;

-- ## ADD COLUMN CONSTRAINTS (NOT NULL)
-- ALTER TABLE student
-- ALTER COLUMN school_id SET NOT NULL;

-- ## DROP COLUMN CONSTRAINTS (NOT NULL)
-- ALTER TABLE student
-- ALTER COLUMN school_id DROP NOT NULL;